# Numpy And Pandas For Data Analysis
### Numpy ndimensional 

In [1]:
import numpy as np
import pandas as pd

In [3]:
a=np.arange(1,50,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [8]:
np.ndarray(9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [27]:
a=[1,2,3,4,5,6,7]
b=np.array(a)
b

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [41]:
a=[1,2,3]
np.ndarray(a)

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.ndim(a)

1

In [24]:
a[2:5]

[3, 4, 5]

In [36]:
list=[]
for i in a:
    list.append(i*2)
print(list)

[2, 4, 6, 8, 10, 12, 14]


In [28]:
type(b)

numpy.ndarray

### Vectorized Operation

In [37]:
b*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [38]:
b.shape

(7,)

In [39]:
b.size

7

In [42]:
lst=[[2,4,5],[5,6,7],[7,8,9]]

In [43]:
lst

[[2, 4, 5], [5, 6, 7], [7, 8, 9]]

In [48]:
arr2d=np.array(lst)
arr2d

array([[2, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [55]:
arr2d[1][1]

6

In [58]:
arr2d=np.arange(36).reshape(4,9)

In [59]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [61]:
arr2d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [63]:
arr2d[0:4,6:9]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [70]:
arr2d[1:,-2]

array([16, 25, 34])

In [71]:
arr2d[:,[4,8,6,2]]

array([[ 4,  8,  6,  2],
       [13, 17, 15, 11],
       [22, 26, 24, 20],
       [31, 35, 33, 29]])

In [72]:
arr2d[[1,3],:]

array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [77]:
arr2d[[0,2],[7,2]]

array([ 7, 20])

In [76]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [78]:
arr2d[:,::2]

array([[ 0,  2,  4,  6,  8],
       [ 9, 11, 13, 15, 17],
       [18, 20, 22, 24, 26],
       [27, 29, 31, 33, 35]])

In [85]:
arr3d=np.arange(64).reshape(4,4,4)

In [86]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [95]:
arr3d[0,1:3,1:3]  # 0 matrix 1th and 2th row and 1th and 2th column

array([[ 5,  6],
       [ 9, 10]])

In [97]:
arr3d[2,1:,0:3]   # 2 matrix all rows starting from 1th row and 0 to 2th column

array([[36, 37, 38],
       [40, 41, 42],
       [44, 45, 46]])

In [99]:
arr3d[0,2,1:3]

array([ 9, 10])

In [100]:
arr3d[1,2,1:3]

array([25, 26])

In [101]:
arr3d[:,2,1:3]

array([[ 9, 10],
       [25, 26],
       [41, 42],
       [57, 58]])

In [107]:
np.zeros((3,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [109]:
np.ones((5,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [121]:
a=np.random.randint(2,10,(3,3))
a

array([[8, 4, 9],
       [6, 2, 5],
       [8, 8, 2]])

In [122]:
b=np.random.randint(1,15,(3,3))
b

array([[ 1, 12,  5],
       [14,  5,  8],
       [ 6,  5, 10]])

In [124]:
a*b

array([[ 8, 48, 45],
       [84, 10, 40],
       [48, 40, 20]])

In [123]:
a+b

array([[ 9, 16, 14],
       [20,  7, 13],
       [14, 13, 12]])

In [130]:
c=np.arange(6).reshape(2,3)

In [131]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [135]:
d=np.arange(6).reshape(3,2)

In [136]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [140]:
c@d

array([[10, 13],
       [28, 40]])

In [147]:
np.full((4,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [148]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [149]:
arr1d=np.arange(10)

In [150]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
arr1d>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [152]:
a=[False, True, False, True, False, True,  False,  True,  False,
        True]

In [154]:
arr1d[a]

array([1, 3, 5, 7, 9])

In [161]:
arr1d[arr1d>5]

array([6, 7, 8, 9])

In [168]:
arr1d[arr1d==5]

array([5])

In [169]:
arr1d[arr1d%2!=0]

array([1, 3, 5, 7, 9])

In [164]:
arr1d[5]

5

In [175]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [176]:
arr2d[arr2d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [177]:
arr2d>10

array([[False, False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [180]:
arr2d[(arr2d>10) & (arr2d<30)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [184]:
arr3d=np.arange(64).reshape(4,4,4)

In [185]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [216]:
arr3d=np.arange(64)

In [217]:
arr3d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [218]:
newravel=arr3d.ravel()
newravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [219]:
flat=arr3d.flatten()
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [221]:
shp=arr3d.reshape(64)
shp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [223]:
flat[0]=10000
flat

array([10000,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63])

In [224]:
newravel[0]=10000

In [225]:
newravel

array([10000,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63])

In [226]:
shp[0]=10000
shp

array([10000,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63])

In [227]:
arr3d

array([10000,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63])

In [228]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [229]:
arr2d1=arr2d[:]*5
arr2d1

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175]])

In [231]:
new2d=np.concatenate([arr2d,arr2d1])
new2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175]])

In [236]:
x=np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [247]:
z=np.arange(1,4)
z

array([1, 2, 3])

In [248]:
x+z

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [249]:
y=np.arange(4).reshape(4,1)
y

array([[0],
       [1],
       [2],
       [3]])

In [250]:
x+y

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

## Pandas 
### Series and DataFrame

In [253]:
import pandas as pd

In [257]:
s1=pd.Series(['ali','ahmed','waqar','qamar','danish'])
s1

0       ali
1     ahmed
2     waqar
3     qamar
4    danish
dtype: object

In [276]:
#Acessing Elements From Series

s1[2]

'waqar'

In [259]:
s1[4]

'danish'

In [260]:
type(s1)

pandas.core.series.Series

In [261]:
type(s1[3])

str

In [263]:
s1[[4,2]]

4    danish
2     waqar
dtype: object

In [265]:
s1[s1=='waqar']  ## Masking

2    waqar
dtype: object

In [270]:
s2=pd.Series([12,24,36,12,24,84,24,36],index=['a','b','c','d','e','f','g','h'])
s2

a    12
b    24
c    36
d    12
e    24
f    84
g    24
h    36
dtype: int64

In [271]:
s2['a']

12

In [273]:
s_multiply=s2*2
s_multiply

a     24
b     48
c     72
d     24
e     48
f    168
g     48
h     72
dtype: int64

In [274]:
s_add=s2+2
s_add

a    14
b    26
c    38
d    14
e    26
f    86
g    26
h    38
dtype: int64

In [277]:
s3=pd.Series([12,24,36,12,24,84,24,36],index=[0,1,2,3,4,5,6,7])

In [279]:
s3

0    12
1    24
2    36
3    12
4    24
5    84
6    24
7    36
dtype: int64

In [280]:
s3.loc[2:6] # follow customized index  loc =location index

2    36
3    12
4    24
5    84
6    24
dtype: int64

In [283]:
s3[2:6]   #follow default index

2    36
3    12
4    24
5    84
dtype: int64

In [285]:
s3.iloc[2:6]    #follow default index   iloc =Integer location index

2    36
3    12
4    24
5    84
dtype: int64

In [286]:
s3+s2

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64

####  NaN type is float

# Alignment|